### ISSUE TITLE
Maintain cursor position

### ISSUE THREAD

**Issue by jbree** [marvhen/ReflowMarkdown#5]
I like to reflow text frequently as I'm writing, but every time I do it leaves the cursor somewhere above where I was last writing. It would be very convenient if, after reflowing, the cursor was left in the same position relative to the reflowed words.

**Comment by marvhen** [comment]
Thanks for the suggestion....I am working on it but it’s proving to be a challenge.

**Comment by jbree** [comment]
Thanks for looking into this. I discovered that the [Rewrap](https://github.com/stkb/Rewrap) plugin accomplishes this already, and indeed supports several other formats as well.

Thanks for your effort! Please don't do it on my behalf, though.
